---
common_packages:
  - alacritty
  - blueman
  - cups
  - dunst
  - fcitx
  - fcitx-googlepinyin
  - fcitx-hangul
  - fcitx-mozc
  - feh
  - fonts-noto
  - fonts-noto-color-emoji
  - fonts-powerline
  - google-chrome-stable
  - linux-image-amd64
  - pavucontrol
  - powertop
  - printer-driver-escpr
  - pulseaudio-module-bluetooth
  - rofi
  - sddm
  - skypeforlinux
  - sway
  - i3status
  - udiskie
  - vagrant
  - wpasupplicant
  - xbacklight
  - xclip
  - xinput
