---
- hosts: local
  tasks:
    - group_by:
        key: "{{ ansible_os_family }}_virt_{{ ansible_virtualization_role|default('none', true) }}"

- hosts: Debian_virt_host
  gather_facts: false
  roles:
    - physical

- hosts: Debian_virt_guest
  gather_facts: false
  roles:
    - common

- hosts: Darwin_virt_none
  gather_facts: false
  roles:
    - mac
