---

- name: Install feh, mpv, pulseaudio-module-bluetooth
  apt:
    name:
      - feh
      - mpv
      - pulseaudio-module-bluetooth
    state: latest
  become: yes

- name: Install blueman on sid
  apt:
    name:
      - blueman
    state: latest
    default_release: sid
  become: yes

- name: Config mpv
  copy:
    src: mpv
    dest: "{{ ansible_user_dir }}/.config/"

- name: Install youtube_dl
  pip:
    name: youtube_dl
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest
