---

- name: Tap repositories
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - koekeishiya/formulae
    - homebrew/cask-fonts

- name: Install packages
  homebrew:
    name: ['ansible', 'jq', 'skhd', 'yabai']
    state: present

- name: Install cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: true
  with_items:
    - alacritty
    - alfred
    - dbeaver-community
    - firefox
    - font-sourcecodepro-nerd-font
    - google-chrome
    - google-japanese-ime
    - insomnia
    - java
    - karabiner-elements
    - vagrant
    - virtualbox

# - name: Allow 'sudo' group to have passwordless sudo
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: '^%admin'
#     line: '%admin		ALL = (ALL) NOPASSWD: ALL'
#     validate: '/usr/sbin/visudo -cf %s'
#   become: yes

- name: Ensure vm_share directory present
  file:
    path: "{{ ansible_user_dir }}/vm_share"
    state: directory
    mode: 0755
