---

- name: Install buil-essential, cmake, curl, fuse, pwgen, socat, unar
  apt:
    name:
      - build-essential
      - cmake
      #- cifs-utils
      - curl
      #- dh-make
      #- git-buildpackage
      #- cowbuilder
      #- dnsutils
      - fuse                    # appimages
      - pwgen
      - socat
      - unar
      #- universal-ctags
      #- zlib1g-dev
    state: latest
  become: yes

- name: Install golang, nnn on sid
  apt:
    name:
      - golang
      - nnn
    state: latest
    default_release: sid
  become: yes

- name: Install python packages of ansible, powerline-status
  pip:
    name:
      - ansible
      #- aws-shell
      #- httpie
      #- mycli==1.18.0
      #- pgcli
      - powerline-status
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

- name: Install node packages of @vue/cli, @bitwarden/cli, joplin
  yarn:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - "@vue/cli"
    - "@bitwarden/cli"
    - joplin
