---

- name: Install ruby-dev
  apt:
    name: ruby-dev
    state: latest
  become: yes

# for install package_cloud
# /usr/bin/ruby2.5: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake (LoadError)
- name: Ensure directory /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe exist
  file:
    path: /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe
    state: directory
  become: yes

- name: Create symbolic link of rake
  file:
    src: /usr/bin/rake
    dest: /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake
    state: link
  become: yes

- name: Install ruby packages of package_cloud, pre-commit
  gem:
    name: "{{ item }}"
    state: latest
  with_items:
    - package_cloud
    - pre-commit
