---

- import_tasks: insomnia.yml
  tags: insomnia

- name: Install dbeaver-ce from flathub for current user
  flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present
    method: user
  tags: dbeaver_ce
