---

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo	ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: ensure config folders exists
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  with_items:
    - .config/ranger
    - .ssh

- name: gitconfig
  copy:
    src: git/config
    dest: "{{ ansible_user_dir }}/.gitconfig"
    force: no

- name: gitignore
  copy:
    src: git/ignore
    dest: "{{ ansible_user_dir }}/.config/git/"
    force: no

- name: config fish
  copy:
    src: fish
    dest: "{{ ansible_user_dir }}/.config/"

- name: set fish as login shell and add docker to groups
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish
    groups: docker
    append: yes
  become: yes

- name: config ranger
  copy:
    src: ranger.rc.conf
    dest: "{{ ansible_user_dir }}/.config/ranger/rc.conf"

- name: config tmux
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"

- name: config ssh
  copy:
    src: ssh_config
    dest: "{{ ansible_user_dir }}/.ssh/config"

- name: config pbuilder
  copy:
    src: pbuilder/pbuilderrc
    dest: "{{ ansible_user_dir }}/.pbuilderrc"

- name: pbuilder hooks
  copy:
    src: pbuilder/hooks
    dest: /var/cache/pbuilder/
  become: yes

- name: config vim
  copy:
    src: vim/
    dest: "{{ ansible_user_dir }}"

- name: config minpac
  git:
    repo: https://github.com/k-takata/minpac.git
    dest: "{{ ansible_user_dir }}/.vim/pack/minpac/opt/minpac"

- name: clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_user_dir }}/.fzf"
    depth: 1

- name: install fzf
  shell: "{{ ansible_user_dir }}/.fzf/install --bin"

- name: install vim plugins
  shell: vim +PackUpdate
