---

- name: config git
  copy: src=gitconfig dest={{ ansible_user_dir }}/.gitconfig

- name: config zsh
  copy: src=zshrc dest={{ ansible_user_dir }}/.zshrc

- name: change login shell
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes

#- name: config vim
#  copy: src=vim/ dest={{ ansible_user_dir }}

#- name: install vim plugins
#  shell: vim -u {{ ansible_user_dir }}/.vim/plugin.vim +PluginInstall +qall
