---

- name: Install backports packages
  apt: name={{ item }} default_release=jessie-backports state=latest
  with_items:
    - powerline
    - tmux
  become: yes

- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
    - zsh
    - vim-nox
    - ranger
    - curl
    - exuberant-ctags
    - cifs-utils
    - apt-transport-https
    - docker-engine
  become: yes
