---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - avahi-daemon
    - build-essential
    - cifs-utils
    - cowbuilder
    - curl
    - dh-make
    - docker-ce
    - exuberant-ctags
    - fish
    - git
    - nodejs
    - openssh-server
    - python3-dev
    - rsync
    - ruby-dev
    - silversearcher-ag
    - tmux
    - unar
    - vim-nox
    - yarn
  become: yes

- name: Install pip packages
  pip:
    name: "{{ item }}"
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
  with_items:
    - mycli
    - pgcli
    - powerline-status
    - ranger-fm

- name: Install gem packages
  gem:
    name: "{{ item }}"
  with_items:
    - package_cloud

- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755
  become: yes

- name: Get latest kubectl version
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
  become: yes
