---

- name: Install packages
  apt:
    name:
      - avahi-daemon
      - build-essential
      - cifs-utils
      - curl
      - dh-make
      - git-buildpackage
      - cowbuilder
      - dnsutils
      - docker-ce
      - fish
      - tmux
      - git
      - kubeadm
      - kubectl
      - kubelet
      - nodejs
      - yarn
      - openssh-server
      - pwgen
      - python3-dev
      - ripgrep
      - rsync
      - ruby-dev
      - unar
      - vim-nox
      - universal-ctags
    state: latest
  become: yes

- name: Install pip packages
  pip:
    name:
      - ansible
      - httpie
      - mycli
      - pgcli
      - powerline-status
      - ranger-fm
      - you-get
      - youtube_dl
    executable: "{{ ansible_user_dir }}/.local/bin/pip"
    extra_args: --user
    state: latest

  # /usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)
- name: symbolic link of rake
  file:
    path: /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe
    state: directory
  become: yes

- file:
    src: /usr/bin/rake
    dest: /usr/share/rubygems-integration/all/gems/rake-12.3.1/exe/rake
    state: link
  become: yes

- name: Install gem packages
  gem:
    name: "{{ item }}"
    state: latest
  with_items:
    - package_cloud
    - rubocop
    - rubocop-rspec
    - solargraph


- name: Install node.js packages
  yarn:
    name:
      - "@vue/cli"
      - javascript-typescript-langserver
      - vue-language-server
      - livedown
    global: yes
    state: latest
