---

- name: Config apt
  copy:
    src: apt/apt.conf
    dest: /etc/apt/
  become: yes

- name: Install curl, htop, openssh-server, rsync, unar
  apt:
    name:
      - curl
      - htop
      - openssh-server
      - rsync
      - unar
    state: latest
  become: yes

- import_tasks: avahi.yml
