---

- name: ensure config folders exists
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  with_items:
    - .config/sway
    - .config/i3status-rs
    - .config/fcitx

  # Enable suspend when connected with external monitor
- name: Ensure "HandleLidSwitchDocked=suspend" in section "[Login]" in specified file
  ini_file:
    path: /etc/systemd/logind.conf
    section: Login
    option: HandleLidSwitchDocked
    value: suspend
    no_extra_spaces: yes
    backup: yes
  become: yes

- name: add lpadmin,systemd-journal groups to user
  user:
    name: "{{ ansible_user_id }}"
    groups: lpadmin,systemd-journal
    append: yes
  become: yes

- name: config alacritty
  copy:
    src: alacritty.yml
    dest: "{{ ansible_user_dir }}/.config/alacritty/"

# - name: sway capabilities
#   capabilities:
#     path: /usr/bin/sway
#     capability: cap_sys_ptrace,cap_sys_tty_config+eip
#     state: present
#   become: yes

- name: config sway
  copy:
    src: sway.config
    dest: "{{ ansible_user_dir }}/.config/sway/config"

- name: start sway
  copy:
    src: start-sway
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: 0755

- name: i3status-rs config
  copy:
    src: i3status-rs-config.toml
    dest: "{{ ansible_user_dir }}/.config/i3status-rs/config.toml"

- name: fcitx config
  copy:
    src: fcitx_config
    dest: "{{ ansible_user_dir }}"/.config/fcitx/config

- name: config mpv
  copy:
    src: mpv
    dest: "{{ ansible_user_dir }}/.config/"

- name: config qutebrowser
  copy:
    src: qutebrowser
    dest: "{{ ansible_user_dir }}/.config/"

- name: create symbolic link to open_url_in_instance.sh
  file:
    src: /usr/share/qutebrowser/scripts/open_url_in_instance.sh
    dest: "{{ ansible_user_dir }}/.local/bin/qutebrowser"
    state: link

- name: umpv
  copy:
    src: umpv
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: 0755
