---

- name: Install common packages
  apt:
    name:
      - alacritty
      - cups
      - cups-browsed
      - fcitx
      - fcitx-config-gtk
      - fcitx-frontend-gtk3
      - fcitx-frontend-qt5
      - fcitx-ui-classic
      - fcitx-googlepinyin
      - fcitx-hangul
      - fcitx-mozc
      - feh
      - fonts-noto
      - fonts-noto-cjk
      - fonts-noto-color-emoji
      - fwupd
      - google-chrome-stable
      - linux-image-amd64
      - libjs-pdf
      - mpv
      - modemmanager
      - network-manager
      - powertop
      - printer-driver-escpr
      - pulseaudio-module-bluetooth
      - qutebrowser
      - skypeforlinux
      - sway
      - swayidle
      - swaylock
      - blueman
      - desktop-base
      - dunst
      - pavucontrol
      - rofi
      - udiskie
      - wl-clipboard
      - xbacklight
      - xclip
      - xwayland
    state: latest
  become: yes

- name: Install sid packages
  apt:
    name: firefox
    state: latest
    default_release: sid
  become: yes

- name: Install peculiar packages
  apt:
    name: "{{ peculiar_packages|default([]) }}"
    state: latest
  become: yes

# - name: Install additional firmwares
#   copy:
#     src: firmware/
#     dest: /lib/firmware/
#   become: yes

- name: ensure local font folder exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory

- name: Install NerdFont
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SourceCodePro/Medium/complete/Sauce%20Code%20Pro%20Medium%20Nerd%20Font%20Complete.ttf
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Sauce Code Pro Medium Nerd Font Complete.ttf"

- name: Check Install NerdFont
  shell: "fc-list | grep Sauce | wc -l"
  register: font_count
  changed_when: False

- name: fc-cache
  shell: "fc-cache -fv"
  when: font_count.stdout|int == 0

- name: purge packages
  apt:
    name:
      - ifupdown
    state: absent
    purge: yes
  become: yes
