---

- name: Install testing packages
  apt:
    name: "{{ item }}"
    state: latest
    default_release: testing
  with_items:
    - dunst
    - udiskie
  become: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - alacritty
    - blueman
    - cups
    - fcitx
    - fcitx-googlepinyin
    - fcitx-hangul
    - fcitx-mozc
    - feh
    - fonts-noto
    - fonts-noto-color-emoji
    - fonts-powerline
    - google-chrome-stable
    - linux-image-amd64
    - pavucontrol
    - powertop
    - printer-driver-escpr
    - pulseaudio-module-bluetooth
    - rofi
    - skypeforlinux
    - sway
    - i3status
    - wpasupplicant
    - xbacklight
  become: yes

- name: Install peculiar packages
  apt:
    name: "{{ item }}"
    state: latest
    default_release: testing
  with_items: "{{ peculiar_packages }}"
  become: yes
